name: toucanto_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sidebarx: ^0.17.1
  fluttertoast: ^8.2.12
  http: ^1.4.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  youtube_explode_dart: ^2.4.1

dependency_overrides:
  meta: ^1.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/files/ffmpeg.exe

  fonts:
    - family: NotosansExtraBold
      fonts:
        - asset: assets/fonts/Notosans-ExtraBold.ttf
    - family: NotosansBold
      fonts:
        - asset: assets/fonts/Notosans-Bold.ttf
    - family: NotosansRegular
      fonts:
        - asset: assets/fonts/Notosans-Regular.ttf
    - family: NotosansLight
      fonts:
        - asset: assets/fonts/Notosans-Light.ttf
    - family: NotosansExtraLight
      fonts:
        - asset: assets/fonts/Notosans-ExtraLight.ttf
    - family: NotosansMedium
      fonts:
        - asset: assets/fonts/Notosans-Medium.ttf
    - family: NotosansSemiBold
      fonts:
        - asset: assets/fonts/Notosans-SemiBold.ttf
    - family: NotosansThin
      fonts:
        - asset: assets/fonts/Notosans-Thin.ttf

