import 'package:flutter_dotenv/flutter_dotenv.dart';

final SUPABASE_URL = dotenv.get('SUPABASE_URL');
final SUPABASE_API_KEY = dotenv.get('SUPABASE_API_KEY');


//Dashboard 외부 저장소 경로
const String STORAGE_NAME = "Toucanto Dashboard";
const String MUSIC_STORAGE_NAME = "Musics";

const String MUSIC_DOWNLOAD_STORAGE_NAME = "Music Downloads";
const String MUSIC_DOWNLOAD_CACHES_NAME = "caches";

const String MUSIC_DOWNLOAD_IDENTIFIED_NAME = "Identified Musics";
const String MUSIC_DOWNLOAD_TEMPORARY_NAME = "Temporary Musics";
const String MUSIC_DOWNLOAD_APPLIER_NAME = "applier";
const String MUSIC_META_DATA_NAME = "";

const List<String> MUSIC_DOWNLOAD_STORAGE_PATH = [STORAGE_NAME, MUSIC_STORAGE_NAME, MUSIC_DOWNLOAD_STORAGE_NAME];
const List<String> MUSIC_DOWNLOAD_PERMANENT_STORAGE_PATH = [STORAGE_NAME, MUSIC_STORAGE_NAME, MUSIC_DOWNLOAD_STORAGE_NAME, MUSIC_DOWNLOAD_IDENTIFIED_NAME];
const List<String> MUSIC_DOWNLOAD_TEMPORARY_STORAGE_PATH = [STORAGE_NAME, MUSIC_STORAGE_NAME, MUSIC_DOWNLOAD_STORAGE_NAME, MUSIC_DOWNLOAD_TEMPORARY_NAME];
const List<String> MUSIC_DOWNLOAD_APPLIER_PATH = [STORAGE_NAME, MUSIC_STORAGE_NAME, MUSIC_DOWNLOAD_STORAGE_NAME, MUSIC_DOWNLOAD_APPLIER_NAME];
const List<String> MUSIC_DOWNLOAD_CACHES_PATH = [STORAGE_NAME, MUSIC_STORAGE_NAME, MUSIC_DOWNLOAD_CACHES_NAME];